// Wallet-local proof state; the mint's view (CheckStateEnum) can't tell a sent-but-unclaimed proof from an owned one
export enum WalletProofState {
	READY = 'READY',
	INFLIGHT = 'INFLIGHT',
	SPENT = 'SPENT',
}

export enum WalletOperationType {
	MINT = 'MINT',
}

export enum WalletOperationState {
	PENDING = 'PENDING',
	EXECUTING = 'EXECUTING',
	FINALIZED = 'FINALIZED',
	FAILED = 'FAILED',
}

// NUT error codes (cashubtc/nuts error_codes.md); cashu-ts exports no constants
export enum CashuMintErrorCode {
	PROOF_VERIFICATION_FAILED = 10001,
	PROOFS_ALREADY_SPENT = 11001,
	PROOFS_PENDING = 11002,
	OUTPUTS_ALREADY_SIGNED = 11003,
	OUTPUTS_PENDING = 11004,
	TRANSACTION_NOT_BALANCED = 11005,
	AMOUNT_OUT_OF_LIMIT = 11006,
	DUPLICATE_INPUTS = 11007,
	DUPLICATE_OUTPUTS = 11008,
	MULTIPLE_UNITS = 11009,
	UNIT_MISMATCH = 11010,
	AMOUNTLESS_INVOICE_UNSUPPORTED = 11011,
	AMOUNT_NOT_INVOICE_AMOUNT = 11012,
	UNIT_UNSUPPORTED = 11013,
	MAX_INPUTS_EXCEEDED = 11014,
	MAX_OUTPUTS_EXCEEDED = 11015,
	DUPLICATE_QUOTE_IDS = 11016,
	MAX_BATCH_SIZE_EXCEEDED = 11017,
	KEYSET_UNKNOWN = 12001,
	KEYSET_INACTIVE = 12002,
	KEYSET_EXPIRED = 12003,
	QUOTE_NOT_PAID = 20001,
	QUOTE_ALREADY_ISSUED = 20002,
	MINTING_DISABLED = 20003,
	LIGHTNING_PAYMENT_FAILED = 20004,
	QUOTE_PENDING = 20005,
	INVOICE_ALREADY_PAID = 20006,
	QUOTE_EXPIRED = 20007,
	MINT_QUOTE_SIGNATURE_INVALID = 20008,
	MINT_QUOTE_PUBKEY_REQUIRED = 20009,
	CLEAR_AUTH_REQUIRED = 30001,
	CLEAR_AUTH_FAILED = 30002,
	BLIND_AUTH_REQUIRED = 31001,
	BLIND_AUTH_FAILED = 31002,
	BAT_MINT_MAX_EXCEEDED = 31003,
	BAT_RATE_LIMIT_EXCEEDED = 31004,
}

// How far a mint quote has progressed for a pending mint operation
export enum MintQuoteProgress {
	MINTABLE = 'MINTABLE',
	ISSUED = 'ISSUED',
	WAITING = 'WAITING',
	EXPIRED = 'EXPIRED',
}

// What a journaled operation does after a mint call fails
export enum WalletErrorAction {
	RESTORE = 'RESTORE',
	CHECK_STATE = 'CHECK_STATE',
	WAIT = 'WAIT',
	REBUILD = 'REBUILD',
	FAIL = 'FAIL',
}
